-- GourmetMate ERD / DDL (PostgreSQL · Neon)
-- ORM: backend/apps/gourmet/adapter/outbound/orm/
-- 규칙: docs/DevOps/Backend/ENTITY_RULE.md (PK = int autoincrement `id`)
--
-- users 테이블은 auth(friday_13th) 소유. FK 참조만 정의합니다.

-- =============================================================================
-- Auth (참조용 — 실제 DDL은 auth 모듈)
-- =============================================================================

CREATE TABLE IF NOT EXISTS users (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(64)  NOT NULL UNIQUE,
    email           VARCHAR(255) NOT NULL UNIQUE,
    nickname        VARCHAR(64)  NOT NULL DEFAULT '',
    password_hash   VARCHAR(255) NOT NULL,
    role            VARCHAR(32)  NOT NULL DEFAULT 'user',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    last_login_at   TIMESTAMPTZ
);

-- =============================================================================
-- 마스터 (2NF / 3NF)
-- =============================================================================

CREATE TABLE IF NOT EXISTS food_categories (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug    VARCHAR(32)  NOT NULL UNIQUE,
    label   VARCHAR(32)  NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS sigungu_districts (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sigungu_name    VARCHAR(32)  NOT NULL DEFAULT '',
    district_label  VARCHAR(128) NOT NULL DEFAULT '',
    CONSTRAINT uq_sigungu_districts_name_label UNIQUE (sigungu_name, district_label)
);

CREATE INDEX IF NOT EXISTS ix_sigungu_districts_district_label
    ON sigungu_districts (district_label);

CREATE TABLE IF NOT EXISTS biz_classifications (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_mid_name    VARCHAR(64)  NOT NULL DEFAULT '',
    biz_minor_name  VARCHAR(128) NOT NULL DEFAULT '',
    ksic_name       VARCHAR(256) NOT NULL DEFAULT '',
    CONSTRAINT uq_biz_classifications_triple UNIQUE (biz_mid_name, biz_minor_name, ksic_name)
);

CREATE INDEX IF NOT EXISTS ix_biz_classifications_ksic
    ON biz_classifications (ksic_name);

CREATE TABLE IF NOT EXISTS tags (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug    VARCHAR(64)  NOT NULL UNIQUE,
    label   VARCHAR(128) NOT NULL DEFAULT ''
);

-- =============================================================================
-- 핵심: restaurants
-- =============================================================================

CREATE TABLE IF NOT EXISTS restaurants (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_number              VARCHAR(48)  NOT NULL UNIQUE,
    name                    TEXT         NOT NULL,
    store_name              TEXT         NOT NULL DEFAULT '',
    branch_name             TEXT         NOT NULL DEFAULT '',
    category_id             INTEGER      NOT NULL
        REFERENCES food_categories (id) ON DELETE RESTRICT,
    sigungu_id              INTEGER      NOT NULL
        REFERENCES sigungu_districts (id) ON DELETE RESTRICT,
    biz_classification_id   INTEGER      NOT NULL
        REFERENCES biz_classifications (id) ON DELETE RESTRICT,
    road_address            TEXT         NOT NULL DEFAULT '',
    parcel_address          TEXT         NOT NULL DEFAULT '',
    latitude                DOUBLE PRECISION,
    longitude               DOUBLE PRECISION,
    description             TEXT         NOT NULL DEFAULT '',
    image_url               VARCHAR(512) NOT NULL DEFAULT '',
    view_count              INTEGER      NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS ix_restaurants_category_sigungu_id
    ON restaurants (category_id, sigungu_id, id);
CREATE INDEX IF NOT EXISTS ix_restaurants_sigungu_id
    ON restaurants (sigungu_id);
CREATE INDEX IF NOT EXISTS ix_restaurants_biz_classification_id
    ON restaurants (biz_classification_id);
CREATE INDEX IF NOT EXISTS ix_restaurants_name
    ON restaurants (name);

-- =============================================================================
-- restaurants 1:1 / 1:N 자식
-- =============================================================================

CREATE TABLE IF NOT EXISTS restaurant_prices (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id   INTEGER NOT NULL UNIQUE
        REFERENCES restaurants (id) ON DELETE CASCADE,
    avg_price       INTEGER
);

CREATE INDEX IF NOT EXISTS ix_restaurant_prices_avg_price
    ON restaurant_prices (avg_price);

CREATE TABLE IF NOT EXISTS restaurant_contacts (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id   INTEGER NOT NULL UNIQUE
        REFERENCES restaurants (id) ON DELETE CASCADE,
    phone           VARCHAR(32),
    place_url       VARCHAR(512),
    source_note     TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS restaurant_menus (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id   INTEGER NOT NULL
        REFERENCES restaurants (id) ON DELETE CASCADE,
    name            VARCHAR(256) NOT NULL DEFAULT '',
    is_signature    BOOLEAN      NOT NULL DEFAULT FALSE,
    sort_order      INTEGER      NOT NULL DEFAULT 0,
    unit_price      INTEGER
);

CREATE INDEX IF NOT EXISTS ix_restaurant_menus_restaurant_id
    ON restaurant_menus (restaurant_id);

CREATE TABLE IF NOT EXISTS restaurant_operating_hours (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id   INTEGER NOT NULL
        REFERENCES restaurants (id) ON DELETE CASCADE,
    weekday         INTEGER NOT NULL,  -- 0=월 … 6=일
    open_time       VARCHAR(8),
    close_time      VARCHAR(8),
    is_closed       BOOLEAN NOT NULL DEFAULT FALSE,
    note            VARCHAR(256) NOT NULL DEFAULT '',
    CONSTRAINT uq_restaurant_operating_hours_day UNIQUE (restaurant_id, weekday)
);

CREATE INDEX IF NOT EXISTS ix_restaurant_operating_hours_restaurant_id
    ON restaurant_operating_hours (restaurant_id);

-- N:M 매장–태그
CREATE TABLE IF NOT EXISTS restaurant_tags (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id   INTEGER NOT NULL
        REFERENCES restaurants (id) ON DELETE CASCADE,
    tag_id          INTEGER NOT NULL
        REFERENCES tags (id) ON DELETE CASCADE,
    CONSTRAINT uq_restaurant_tags_pair UNIQUE (restaurant_id, tag_id)
);

CREATE INDEX IF NOT EXISTS ix_restaurant_tags_restaurant_id
    ON restaurant_tags (restaurant_id);
CREATE INDEX IF NOT EXISTS ix_restaurant_tags_tag_id
    ON restaurant_tags (tag_id);

-- 레거시 조회 통계 (restaurants.view_count 와 별도)
CREATE TABLE IF NOT EXISTS restaurant_view_stats (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id       INTEGER NOT NULL UNIQUE
        REFERENCES restaurants (id) ON DELETE CASCADE,
    view_count          INTEGER NOT NULL DEFAULT 0,
    first_viewed_at     TIMESTAMPTZ,
    last_viewed_at      TIMESTAMPTZ
);

-- =============================================================================
-- 사용자 연동
-- =============================================================================

CREATE TABLE IF NOT EXISTS favorites (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INTEGER NOT NULL
        REFERENCES users (id) ON DELETE CASCADE,
    restaurant_id   INTEGER NOT NULL
        REFERENCES restaurants (id) ON DELETE CASCADE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_favorites_user_restaurant UNIQUE (user_id, restaurant_id)
);

CREATE INDEX IF NOT EXISTS ix_favorites_user_id ON favorites (user_id);
CREATE INDEX IF NOT EXISTS ix_favorites_restaurant_id ON favorites (restaurant_id);

CREATE TABLE IF NOT EXISTS meal_plans (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INTEGER NOT NULL
        REFERENCES users (id) ON DELETE CASCADE,
    monthly_budget  INTEGER NOT NULL,
    spent_amount    INTEGER NOT NULL DEFAULT 0,
    period_start    DATE NOT NULL,
    period_end      DATE NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_meal_plans_user_id ON meal_plans (user_id);
CREATE INDEX IF NOT EXISTS ix_meal_plans_period_start ON meal_plans (period_start);
CREATE INDEX IF NOT EXISTS ix_meal_plans_period_end ON meal_plans (period_end);

-- 유저별 일일 AI 추천 1곳
CREATE TABLE IF NOT EXISTS daily_recommendations (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INTEGER NOT NULL
        REFERENCES users (id) ON DELETE CASCADE,
    restaurant_id   INTEGER NOT NULL
        REFERENCES restaurants (id) ON DELETE CASCADE,
    meal_plan_id    INTEGER
        REFERENCES meal_plans (id) ON DELETE SET NULL,
    recommended_on  DATE NOT NULL,
    pick_reason     TEXT NOT NULL DEFAULT '',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_daily_rec_user_date UNIQUE (user_id, recommended_on)
);

CREATE INDEX IF NOT EXISTS ix_daily_recommendations_user_id
    ON daily_recommendations (user_id);
CREATE INDEX IF NOT EXISTS ix_daily_recommendations_restaurant_id
    ON daily_recommendations (restaurant_id);
CREATE INDEX IF NOT EXISTS ix_daily_recommendations_meal_plan_id
    ON daily_recommendations (meal_plan_id);
CREATE INDEX IF NOT EXISTS ix_daily_recommendations_recommended_on
    ON daily_recommendations (recommended_on);

-- =============================================================================
-- 운영 / 추천 (유저 무관)
-- =============================================================================

-- 날짜별 오늘의 맛집 N선
CREATE TABLE IF NOT EXISTS daily_picks (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pick_date       DATE    NOT NULL,
    restaurant_id   INTEGER NOT NULL
        REFERENCES restaurants (id) ON DELETE CASCADE,
    rank            INTEGER NOT NULL,
    CONSTRAINT uq_daily_pick_date_restaurant UNIQUE (pick_date, restaurant_id),
    CONSTRAINT uq_daily_pick_date_rank UNIQUE (pick_date, rank)
);

CREATE INDEX IF NOT EXISTS ix_daily_picks_pick_date ON daily_picks (pick_date);
CREATE INDEX IF NOT EXISTS ix_daily_picks_restaurant_id ON daily_picks (restaurant_id);

CREATE TABLE IF NOT EXISTS search_query_logs (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query               VARCHAR(128) NOT NULL,
    query_normalized    VARCHAR(128) NOT NULL,
    result_count        INTEGER NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_search_query_logs_query ON search_query_logs (query);
CREATE INDEX IF NOT EXISTS ix_search_query_logs_query_normalized
    ON search_query_logs (query_normalized);
CREATE INDEX IF NOT EXISTS ix_search_query_logs_created_at ON search_query_logs (created_at);
