from typing import Any, Protocol


class TitanicQueryPort(Protocol):
    def get_data(self) -> dict[str, Any]: ...

    def get_count(self) -> int: ...

    def get_count_survived(self) -> int: ...

    def get_count_dead(self) -> int: ...

    def has_decision_tree_model(self) -> bool: ...

    def get_training_model_name(self) -> str: ...

    def get_training_model_accuracy(self) -> float: ...
